name: Test clutchless

on:
  create:
    branches: [ master ]
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.0.10

      - name: Install with poetry
        run: |
          poetry config --local virtualenvs.in-project true
          poetry install

      - name: Run pytest for unit tests
        run: |
          source .venv/bin/activate
          coverage run --source=clutchless -m pytest $GITHUB_WORKSPACE/tests/unit

      - name: Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
        run: |
          source .venv/bin/activate
          coveralls

#       - name: Coveralls
#         uses: coverallsapp/github-action@master
#         with:
#           github-token: ${{ secrets.COVERALLS_TOKEN }}
#           path-to-lcov: ./.coverage
